version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - errcheck
    - gocognit
    - goconst
    - gosec
    - govet
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - nolintlint
    - prealloc
    - staticcheck
    - tagliatelle
    - unconvert
    - unparam
  settings:
    errcheck:
      check-type-assertions: true
    goconst:
      min-len: 2
      min-occurrences: 2
    misspell:
      locale: US
    nolintlint:
      require-explanation: true
      require-specific: true
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake
    unparam:
      check-exported: false
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
        path: _test\.go
      - linters:
          - gosec
        path: _test\.go
        text: 'G404: Use of weak random number generator'
      - path: (.+)\.go$
        text: G104
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/arwoosa/vulpes
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
